#!/usr/bin/env ruby

require 'pandoc-ruby'

converter = PandocRuby.convert(
  [
    File.join(File.dirname(__FILE__), '../Intro.md'),
    File.join(File.dirname(__FILE__), '../../project-procedure/README.md'),
    File.join(File.dirname(__FILE__), '../../project-procedure/digital-products/README.md'),
    File.join(File.dirname(__FILE__), '../../development-process/README.md')
  ],
  :standalone,
  :toc,
  {
    :from => :markdown,
    :to => :html,
    :output => "#{File.dirname(__FILE__)}/../../dist/index.html"
  }
)
