#!/usr/bin/env ruby
require 'fileutils'

require 'pandoc-ruby'

def read_md_source(file)
  source = File.read("#{File.dirname(__FILE__)}/#{file}")
  source.gsub(/\[(.*?)\]\((.*?)#(.*?)\)/m, '[\1](#\3)')
  source.gsub(/\!\[(.*?)\]\([.\/]+(.*?)\)/m, '![\1](./\2)')
end

input = <<-MD
#{read_md_source('../Intro.md')}
#{read_md_source('../../project-procedure/README.md')}
#{read_md_source('../../project-procedure/digital-products/README.md')}
#{read_md_source('../../development-process/README.md')}
MD

FileUtils.cp_r "#{File.dirname(__FILE__)}/../../assets", 'dist/assets'

PandocRuby.convert(
  input,
  :standalone,
  :toc,
  {
    :from => :markdown,
    :to => :html,
    :output => "#{File.dirname(__FILE__)}/../../dist/index.html"
  }
)
