---
language: node_js
node_js:
  - "8"

sudo: false
dist: trusty

cache:
  yarn: true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install --non-interactive --pure-lockfile

jobs:
  include:
    - stage: test
      name: Tests
      script: yarn lint

notifications:
  email: false
