name: CI

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  compile:
    name: Compilation
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          cache: yarn

      - name: Install Prince
        run: |
          wget https://www.princexml.com/download/prince_20200304-1_ubuntu18.04_amd64.deb -O /tmp/prince.deb
          sudo apt install /tmp/prince.deb

      - name: install dependencies
        run: yarn install

      - name: prepare
        run: yarn prepare-book

      - name: compile
        run: yarn compile-book

      - uses: actions/upload-artifact@v1
        with:
          name: Book
          path: dist/book.pdf
